"""Validated contracts for external model-service operations."""

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import Field, StringConstraints

from applied_genai.schemas.base import ApiSchema
from applied_genai.schemas.prompt import (
    GeneratedText,
    GenerationFinishReason,
    ModelIdentifier,
)

ExternalServiceName = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        min_length=1,
        max_length=100,
    ),
]


class ExternalServiceHealthStatus(StrEnum):
    """Supported health states returned by an external model service."""

    HEALTHY = "healthy"


class ExternalServiceHealthResponse(ApiSchema):
    """Validated health response from an external model service."""

    service: ExternalServiceName = Field(
        description="Human-readable external service name.",
        examples=["mock-model-service"],
    )
    status: ExternalServiceHealthStatus = Field(
        description="Current health state of the external service.",
    )


class ModelServiceStatusResponse(ApiSchema):
    """API response confirming model-service availability."""

    available: Literal[True] = Field(
        default=True,
        description="Indicates that the external model service is available.",
    )
    upstream: ExternalServiceHealthResponse = Field(
        description="Validated health information returned by the upstream service.",
    )


class ExternalModelGenerationResponse(ApiSchema):
    """Validated generation response returned by the model service."""

    model_id: ModelIdentifier = Field(
        description="Identifier of the model used by the upstream service.",
    )
    generated_text: GeneratedText = Field(
        description="Text generated by the upstream model.",
    )
    prompt_tokens: int = Field(
        ge=0,
        description="Number of input tokens processed upstream.",
    )
    completion_tokens: int = Field(
        ge=0,
        description="Number of output tokens generated upstream.",
    )
    finish_reason: GenerationFinishReason = Field(
        description="Reason the upstream generation operation ended.",
    )
