"""Validated schemas for Applied GenAI prompt operations."""

from enum import StrEnum
from typing import Annotated, Literal, Self

from pydantic import (
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)

from applied_genai.schemas.base import ApiSchema

PromptText = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        min_length=1,
        max_length=4000,
    ),
]

SystemPromptText = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        min_length=1,
        max_length=2000,
    ),
]

ModelIdentifier = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        min_length=1,
        max_length=128,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
    ),
]

StopSequence = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        min_length=1,
        max_length=100,
    ),
]

GeneratedText = Annotated[
    str,
    StringConstraints(
        min_length=1,
        max_length=100000,
    ),
]


class GenerationFinishReason(StrEnum):
    """Supported reasons for ending model generation."""

    STOP = "stop"
    LENGTH = "length"


class PromptRequest(ApiSchema):
    """Validated request for a language-model operation."""

    prompt: PromptText = Field(
        description="User instruction or question submitted to the model.",
        examples=["Explain retrieval-augmented generation."],
    )
    model_id: ModelIdentifier = Field(
        default="local/default",
        description="Identifier of the model that should process the request.",
        examples=["qwen2.5:3b"],
    )
    system_prompt: SystemPromptText | None = Field(
        default=None,
        description="Optional instruction defining the model's behavior.",
        examples=["Answer as a concise infrastructure engineer."],
    )
    temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=2.0,
        description="Sampling temperature used during model generation.",
    )
    max_tokens: int = Field(
        default=512,
        ge=1,
        le=4096,
        description="Maximum number of tokens that may be generated.",
    )
    stop_sequences: list[StopSequence] = Field(
        default_factory=list,
        max_length=8,
        description="Optional sequences that stop model generation.",
    )

    @field_validator("stop_sequences")
    @classmethod
    def validate_unique_stop_sequences(
        cls,
        value: list[str],
    ) -> list[str]:
        """Reject duplicate stop sequences after normalization."""
        if len(value) != len(set(value)):
            raise ValueError("Stop sequences must be unique.")

        return value


class PromptValidationResponse(ApiSchema):
    """Response confirming that a prompt request passed validation."""

    valid: Literal[True] = Field(
        default=True,
        description="Indicates that the request passed validation.",
    )
    request: PromptRequest = Field(
        description="Normalized and validated prompt request.",
    )


class TokenUsage(ApiSchema):
    """Token usage reported for one generation operation."""

    prompt_tokens: int = Field(
        ge=0,
        description="Number of input tokens processed.",
    )
    completion_tokens: int = Field(
        ge=0,
        description="Number of output tokens generated.",
    )
    total_tokens: int = Field(
        ge=0,
        description="Combined input and output token count.",
    )

    @model_validator(mode="after")
    def validate_total_tokens(self) -> Self:
        """Ensure total tokens equal prompt plus completion tokens."""
        expected_total = self.prompt_tokens + self.completion_tokens

        if self.total_tokens != expected_total:
            raise ValueError(
                "total_tokens must equal prompt_tokens plus completion_tokens.",
            )

        return self


class PromptGenerationResponse(ApiSchema):
    """Public response returned after model generation."""

    model_id: ModelIdentifier = Field(
        description="Identifier of the model that generated the response.",
    )
    generated_text: GeneratedText = Field(
        description="Text generated by the external model service.",
    )
    finish_reason: GenerationFinishReason = Field(
        description="Reason model generation stopped.",
    )
    usage: TokenUsage = Field(
        description="Token usage reported for the generation operation.",
    )
